port: {{ default(global.clash.http_port, "7890") }}
socks-port: {{ default(global.clash.socks_port, "7891") }}
allow-lan: {{ default(global.clash.allow_lan, "true") }}
mode: rule
log-level: {{ default(global.clash.log_level, "info") }}
external-controller: :9090

{% if default(request.adg, "true") == "true" or exists("request.adg.port") %}
dns:
  enable: true
  ipv6: false
  listen: 127.0.0.1:{{ default(request.adg.port, "5450") }}
  enhanced-mode: redir-host
  default-nameserver:
    - 119.29.29.29
    - 119.28.28.28
    - 223.5.5.5
    - 223.6.6.6
    - 1.12.12.12
  nameserver:
    - https://doh.yyaan.com/dns-query
    - https://dns.alidns.com/dns-query
    - https://doh.pub/dns-query
    fallback:
    - https://yyaan.top/dns-query
    - https://dns64.cloudflare-dns.com/dns-query
    - https://dns64.dns.google/dns-query
    - https://dns.google/dns-query
    - https://cloudflare-dns.com/dns-query
{% endif %}

{% if local.clash.new_field_name == "true" %}
proxies: ~
proxy-groups: ~
rules: ~
{% else %}
Proxy: ~
Proxy Group: ~
Rule: ~
{% endif %}
